version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: data_base
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coins
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U your_user -d your_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pkg/migrations/postgres:/docker-entrypoint-initdb.d
    restart: always
