version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: cryptodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/adapters/storage/postgres/migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crypto_user -d cryptodb"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      bash -c "
      docker-entrypoint.sh postgres &
      while ! pg_isready -U crypto_user -d cryptodb; do sleep 1; done
      cd /migrations
      for f in *.sql; do
        psql -U crypto_user -d cryptodb -f $$f
      done
      wait
      "

volumes:
  postgres_data: